language: node_js
node_js:
  - "node"
deploy:
  - provider: script
    script: sh deploy.sh production
    on:
      branch: master
  - provider: script
    script: sh deploy.sh dev
    on:
      branch: develop