
service: serverless-boilerplate-service

app: serverless-boilerplate-app
tenant: ${env:TENANT}
provider:
  name: aws
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
  environment:
    EXAMPLE_TABLE: ${self:custom.exampleTable}

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stages:
    dev:
      domain: ${env:DEV_DOMAIN}
      domainEnabled: true
      certificateName: ${env:DEV_CERTIFICATE_NAME}
    production:
      domain: ${env:PROD_DOMAIN}
      domainEnabled: true
      certificateName: ${env:PROD_CERTIFICATE_NAME}
  exampleTable: '${self:service}-example-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
      seed: true
  customDomain:
    domainName: ${self:custom.stages.${self:provider.stage}.domain}
    certificateName: ${self:custom.stages.${self:provider.stage}.certificateName}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    enabled: ${self:custom.stages.${self:provider.stage}.domainEnabled}
  dotenv:
    include:
      - NONE

functions:
  app:
    handler: handler.app
    events:
        - http: ANY /
        - http: 'ANY {proxy+}'

resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        # It is usually preferable to use the PAY_PER_REQUEST billing
        # mode instead of specifying a provisioned throughput.
        # Unfortunately the serverless-dynamodb-local module do not support
        # it yet. So in the mean we keep using provisioned capacity.
        # BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:custom.exampleTable}
